[theme]
primaryColor = "#8a2be2"
backgroundColor = "#f5f7f9"
secondaryBackgroundColor = "#e6eaf1"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false 